### ISSUE TITLE
Test suite fails (since Dancer 1.3510?)

### ISSUE THREAD

**Issue by eserte** [SysPete/Dancer-Plugin-PageHistory#1] opened 2019-03-22 22:20 UTC
t/plugin.t started to fail on my smoker systems:
```
# Dancer::Session::CHI missing so not testing this session engine
# Dancer::Session::Cookie missing so not testing this session engine
# Dancer::Session::DBIC missing so not testing this session engine
# Dancer::Session::JSON missing so not testing this session engine
# Dancer::Session::Memcached missing so not testing this session engine
# Dancer::Session::Memcached::Fast missing so not testing this session engine
# Dancer::Session::MongoDB missing so not testing this session engine
# Dancer::Session::PSGI missing so not testing this session engine
# Testing with Simple

#   Failed test 'get /one OK'
#   at t/plugin.t line 43.
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "<!DOCTYPE html PUBLI...") at t/plugin.t line 45.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 2 just after 26.
t/plugin.t ........ 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 1/26 subtests 
```

This seems to happen with Dancer 1.3510; earlier Dancer versions seem to be OK (@bigpresh: FYI). Statistical analysis (theta = -1 means "bad"):
```
****************************************************************
Regression 'mod:Dancer'
****************************************************************
Name           	       Theta	      StdErr	 T-stat
[0='const']    	      1.0000	      0.0000	20313919873920684.00
[1='eq_1.3126']	     -0.0000	      0.0000	  -1.40
[2='eq_1.3136']	     -0.0000	      0.0000	  -1.40
[3='eq_1.3138']	     -0.0000	      0.0000	  -1.87
[4='eq_1.3140']	     -0.0000	      0.0000	  -1.89
[5='eq_1.3142']	     -0.0000	      0.0000	  -1.90
[6='eq_1.3202']	     -0.0000	      0.0000	  -2.24
[7='eq_1.3400']	     -0.0000	      0.0000	  -1.84
[8='eq_1.3500']	      0.0000	      0.0000	   0.00
[9='eq_1.3510']	     -1.0000	      0.0000	-19449097552081872.00

R^2= 1.000, N= 138, K= 10
****************************************************************
```

**Comment by bigpresh** [comment] 2019-03-25 22:44
Just to say I'm looking in to this - it appears changes in Dancer 1.3510 are responsible for this. Concerningly, even though Dancer's own comprehensive session tests pass fine with the changes, it appears to have caused this problem here, and also something similar in Dancer::Plugin::Auth::Extensible.

In other words, I don't believe there to be a problem with Dancer::Plugin::PageHistory, and I'm on it.

**Comment by bigpresh** [comment] 2019-03-31 19:02
I can confirm that this was caused by changes in Dancer 1.3510, and that it passes against the current dev release 1.3511 which will be released as a stable release in the next couple of days, so this ticket could be closed.

**Comment by SysPete** [comment] 2020-02-04 17:22
Thank you @bigpresh 

/me finally tries to catch up on ancient tickets

**Closed as completed by SysPete** 2020-02-04 17:22 UTC
